### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by bmcurutan** [AleBiancaIta/Pulse#3]
This issue refers to both the frontend and backend of user login with Parse integration

Frontend: Login page and sign up page (and maybe reset password page, or put it in the same page)

Required:
- User must be able to login using their username and password
- Link to go to sign up page if user does not have an account
- User can skip login and use the app anonymously, locally, without signing up
- User must be able to logout

Optional: 
- Reset password functionality/ Link to go to a page to reset password
- User can login with touch ID
- User can sign up using Google or Facebook authentication
- User can add their company to be able to sync up with other users within the company

Backend: Parse

Sync up with Ale since she's doing the person details page and only one of you needs to create the database schema for person

**Comment by itasari** [comment]
Log Out capability is moved to the Settings page since the user don't usually go back to Login/SignUp view once they're inside the app. I also moved the reset password to optional.

Note: as part of the sign up process, a Person object related to the new user ID is created in Parse.
